// Terminology explanations grounded in the existing 2:197 token-26 analysis.
// These describe the displayed construction, not new dependency annotations.
export const SYNTAX_TERMS = {
  inna: { ar: 'إِنَّ', tr: 'inna', words: [23], tone: 'a', aliases: ['إِنَّ'], ru: ['Частица, которая вводит и усиливает утверждение.', 'В этой фразе после неё названы خَيْرَ ٱلزَّادِ — «лучший запас», а ٱلتَّقْوَىٰ завершает сообщение о нём.'], en: ['A particle that introduces and emphasizes a statement.', 'Here خَيْرَ ٱلزَّادِ names “the best provision,” and ٱلتَّقْوَىٰ completes the statement about it.'] },
  ismInna: { ar: 'اسْم إِنَّ', tr: 'ism inna', words: [24], tone: 'a', aliases: ['اسم إِنَّ', 'ism inna'], ru: ['Именная часть конструкции с إِنَّ: то, о чём делается утверждение.', 'Здесь эту роль выполняет خَيْرَ. Оно стоит в винительном падеже и одновременно является первым словом идафы خَيْرَ ٱلزَّادِ.'], en: ['The nominal argument of إِنَّ: what the statement is about.', 'Here this role belongs to خَيْرَ. It is accusative and also the first noun in the iḍāfa خَيْرَ ٱلزَّادِ.'] },
  mudaf: { ar: 'مُضَاف', tr: 'muḍāf', words: [24], tone: 'a', aliases: ['مُضَاف', 'مُضاف', 'muḍāf'], ru: ['Первое слово идафы; следующее существительное уточняет его.', 'Здесь это خَيْرَ — «лучший». ٱلزَّادِ указывает, о чём говорится: «лучший запас». Винительный падеж خَيْرَ связан с его ролью اسم إِنَّ.'], en: ['The first noun of an iḍāfa, specified by the noun that follows.', 'Here it is خَيْرَ, “best.” ٱلزَّادِ specifies provision. The accusative of خَيْرَ comes from its role as ism inna.'] },
  mudafIlayhi: { ar: 'مُضَاف إِلَيْهِ', tr: 'muḍāf ilayhi', words: [25], tone: 'b', aliases: ['مُضَاف إِلَيْهِ', 'مُضاف إليه', 'muḍāf ilayhi'], ru: ['Второе слово идафы: оно уточняет первое и стоит в родительном падеже.', 'Здесь это ٱلزَّادِ — «запас». Оно соединяется с خَيْرَ в одну конструкцию. Именно ٱلزَّادِ, а не вся фраза, выделено как مُضَاف إِلَيْهِ.'], en: ['The second noun of an iḍāfa. It specifies the first and takes the genitive case.', 'Here it is ٱلزَّادِ, “provision.” This word, rather than the whole phrase, is highlighted as muḍāf ilayhi.'] },
  idafa: { ar: 'إِضَافَة', tr: 'iḍāfa', words: [24,25], tone: 'a', aliases: ['идафу', 'идафы', 'идафа', 'iḍāfa'], ru: ['Соединение двух существительных: второе уточняет первое.', 'В خَيْرَ ٱلزَّادِ первое слово — مُضَاف, второе — مُضَاف إِلَيْهِ. Вместе они обозначают «лучший запас».'], en: ['A construction in which the second noun specifies the first.', 'In خَيْرَ ٱلزَّادِ, the first is muḍāf and the second is muḍāf ilayhi. Together they name “the best provision.”'] },
  khabarInna: { ar: 'خَبَر إِنَّ', tr: 'khabar inna', words: [26], tone: 'c', aliases: ['خبر إِنَّ','khabar inna'], ru: ['Часть конструкции с إِنَّ, которая сообщает что-либо об её именной части и завершает утверждение.', 'Здесь ٱلتَّقْوَىٰ сообщает, чем является «лучший запас». Это слово грамматически стоит в именительном падеже, хотя дамма на конечной ىٰ не видна.'], en: ['The part that completes the statement about the nominal argument of إِنَّ.', 'Here ٱلتَّقْوَىٰ says what “the best provision” is. It is nominative, although its final ىٰ does not display a ḍamma.'] },
  accusative: { ar: 'مَنْصُوب', tr: 'manṣūb', words: [24], tone: 'a', aliases: ['винительном падеже','Винительный падеж','accusative'], ru: ['Название падежной формы: винительный падеж.', 'В этой фразе خَيْرَ стоит в такой форме как اسم إِنَّ. Здесь название падежа объясняет грамматическое положение слова.'], en: ['The accusative grammatical case.', 'Here خَيْرَ has this case because it is ism inna. The case describes its grammatical position in this construction.'] },
  genitive: { ar: 'مَجْرُور', tr: 'majrūr', words: [25], tone: 'b', aliases: ['родительном падеже','genitive'], ru: ['Название падежной формы: родительный падеж.', 'В этой конструкции ٱلزَّادِ принимает его как مُضَاف إِلَيْهِ — второе слово идафы.'], en: ['The genitive grammatical case.', 'Here ٱلزَّادِ takes this case as muḍāf ilayhi, the second noun of the iḍāfa.'] },
  nominative: { ar: 'مَرْفُوع', tr: 'marfūʿ', words: [26], tone: 'c', aliases: ['именительном падеже','nominative'], ru: ['Название падежной формы: именительный падеж.', 'Здесь ٱلتَّقْوَىٰ имеет эту форму как خبر إِنَّ. Её показатель, дамма, не появляется на конечной ىٰ.'], en: ['The nominative grammatical case.', 'Here ٱلتَّقْوَىٰ is nominative as khabar inna. Its case marker, ḍamma, does not appear on the final ىٰ.'] },
  damma: { ar: 'ضَمَّة مُقَدَّرَة', tr: 'ḍamma muqaddara', words: [26], tone: 'c', aliases: ['дамма','ḍamma'], ru: ['Подразумеваемая дамма: падеж определяется грамматически, но огласовка не видна и отдельно не произносится.', 'تَقْوَىٰ заканчивается на ىٰ (alif maqṣūra). Поэтому его именительный падеж здесь нельзя определить по видимому значку ُ — его объясняет роль خبر إِنَّ.'], en: ['An understood ḍamma: the case is grammatically present, but the vowel is not written or pronounced separately.', 'تَقْوَىٰ ends in ىٰ (alif maqṣūra). Its nominative case is understood from its role as khabar inna.'] },
  alif: { ar: 'أَلِف مَقْصُورَة', tr: 'alif maqṣūra', words: [26], tone: 'c', aliases: ['alif maqṣūra'], ru: ['Название конечной буквы ىٰ в تَقْوَىٰ.', 'В существующем разборе именно это окончание объясняет, почему дамма в именительном падеже не видна и отдельно не произносится.'], en: ['The name of the final letter ىٰ in تَقْوَىٰ.', 'In this analysis, this ending explains why the nominative ḍamma is not displayed or separately pronounced.'] },
}
export const STEP_ROLES = {
  inna: [{ word:23, term:'inna' }, { word:24, term:'ismInna' }],
  idafa: [{ word:24, term:'mudaf' }, { word:25, term:'mudafIlayhi' }],
  predicate: [{ word:24, term:'ismInna' }, { word:25, term:'mudafIlayhi' }, { word:26, term:'khabarInna' }],
}
