// Terminology explanations grounded in the existing 2:197 token-26 analysis.
// These describe the displayed construction, not new dependency annotations.
export const SYNTAX_TERMS = {
  inna: { ar: 'إِنَّ', tr: 'inna', words: [23], tone: 'a', aliases: ['إِنَّ'], ru: ['Частица, которая вводит и усиливает утверждение.', 'В этой фразе после إِنَّ (inna) идёт خَيْرَ ٱلزَّادِ (khayra al-zādi) — «лучший запас», а ٱلتَّقْوَىٰ (al-taqwā) завершает сообщение о нём.'], en: ['A particle that introduces and emphasizes a statement.', 'Here خَيْرَ ٱلزَّادِ names “the best provision,” and ٱلتَّقْوَىٰ completes the statement about it.'] },
  ismInna: { ar: 'اسْم إِنَّ', tr: 'ism inna', words: [24], tone: 'a', aliases: ['اسم إِنَّ', 'ism inna'], ru: ['Именная часть конструкции с إِنَّ (inna): то, о чём делается утверждение.', 'Здесь эту роль выполняет خَيْرَ (khayra). После إِنَّ оно находится в состоянии manṣūb и одновременно является первым словом идафы خَيْرَ ٱلزَّادِ (khayra al-zādi).'], en: ['The nominal argument of إِنَّ: what the statement is about.', 'Here this role belongs to خَيْرَ. It is accusative and also the first noun in the iḍāfa خَيْرَ ٱلزَّادِ.'] },
  mudaf: { ar: 'مُضَاف', tr: 'muḍāf', words: [24], tone: 'a', aliases: ['مُضَاف', 'مُضاف', 'muḍāf'], ru: ['Первое слово идафы; следующее существительное уточняет его.', 'Здесь это خَيْرَ (khayra) — «лучший». ٱلزَّادِ (al-zādi) уточняет его: вместе خَيْرَ ٱلزَّادِ (khayra al-zādi) означает «лучший запас». Состояние manṣūb у خَيْرَ связано с его ролью اسم إِنَّ (ism inna).'], en: ['The first noun of an iḍāfa, specified by the noun that follows.', 'Here it is خَيْرَ, “best.” ٱلزَّادِ specifies provision. The accusative of خَيْرَ comes from its role as ism inna.'] },
  mudafIlayhi: { ar: 'مُضَاف إِلَيْهِ', tr: 'muḍāf ilayhi', words: [25], tone: 'b', aliases: ['مُضَاف إِلَيْهِ', 'مُضاف إليه', 'muḍāf ilayhi'], ru: ['Второе слово идафы: оно уточняет первое и получает состояние majrūr.', 'Здесь это ٱلزَّادِ (al-zādi) — «запас». Оно соединяется с خَيْرَ (khayra) в одну конструкцию. Именно ٱلزَّادِ, а не вся фраза, выполняет роль مُضَاف إِلَيْهِ (muḍāf ilayhi).'], en: ['The second noun of an iḍāfa. It specifies the first and is in the majrūr state.', 'Here it is ٱلزَّادِ, “provision.” This word, rather than the whole phrase, is highlighted as muḍāf ilayhi.'] },
  idafa: { ar: 'إِضَافَة', tr: 'iḍāfa', words: [24,25], tone: 'a', aliases: ['идафу', 'идафы', 'идафа', 'iḍāfa'], ru: ['Соединение двух существительных: второе уточняет первое.', 'В خَيْرَ ٱلزَّادِ (khayra al-zādi) خَيْرَ (khayra) — مُضَاف (muḍāf), а ٱلزَّادِ (al-zādi) — مُضَاف إِلَيْهِ (muḍāf ilayhi). Вместе они обозначают «лучший запас».'], en: ['A construction in which the second noun specifies the first.', 'In خَيْرَ ٱلزَّادِ, the first is muḍāf and the second is muḍāf ilayhi. Together they name “the best provision.”'] },
  khabarInna: { ar: 'خَبَر إِنَّ', tr: 'khabar inna', words: [26], tone: 'c', aliases: ['خبر إِنَّ','khabar inna'], ru: ['Часть конструкции с إِنَّ (inna), которая сообщает что-либо об её именной части и завершает утверждение.', 'Здесь ٱلتَّقْوَىٰ (al-taqwā) сообщает, чем является خَيْرَ ٱلزَّادِ (khayra al-zādi) — «лучший запас». В этой роли слово находится в состоянии marfūʿ; из-за конечной ىٰ видимая ḍamma не появляется.'], en: ['The part that completes the statement about the nominal argument of إِنَّ.', 'Here ٱلتَّقْوَىٰ says what “the best provision” is. It is in the marfūʿ state, although its final ىٰ does not display a ḍamma.'] },
  accusative: { ar: 'مَنْصُوب', tr: 'manṣūb', words: [24], tone: 'a', aliases: ['manṣūb','مَنْصُوب'], ru: ['Manṣūb — состояние, которое слово получает не потому, что оно «само по себе такое», а потому что его поставили в определённую грамматическую роль или на него подействовал другой элемент конструкции.', 'Как определить: сначала ищем функцию слова. Manṣūb часто получают, например, прямой объект действия (مفعول به), имя после إِنَّ и её сестёр (اسم إِنَّ), а также некоторые обстоятельственные и поясняющие роли. Поэтому одного универсального вопроса вроде «кого? что?» здесь нет: такой вопрос подходит только для некоторых ролей, например для прямого объекта.', 'В нашей фразе إِنَّ (inna) — элемент, который меняет состояние своей именной части. خَيْرَ (khayra) — اسم إِنَّ (ism inna), то есть то, о чём начинается утверждение после إِنَّ. Именно эта роль делает خَيْرَ manṣūb. После того как роль определена, уже смотрим на форму: здесь это видно по окончанию -a / fatḥa — khayra.'], en: ['Manṣūb is a state a word receives because of its syntactic role or because another element governs it.', 'To identify it, first determine the word’s function. Common manṣūb roles include the direct object, اسم إِنَّ after إِنَّ and its sisters, and several adverbial or specifying functions. There is no single universal question that defines manṣūb.', 'Here إِنَّ (inna) governs its nominal element. خَيْرَ (khayra) is اسم إِنَّ (ism inna), so that role makes it manṣūb. Only after identifying the role do we look at the form: here the final -a / fatḥa shows it.'] },
  genitive: { ar: 'مَجْرُور', tr: 'majrūr', words: [25], tone: 'b', aliases: ['majrūr','مَجْرُور'], ru: ['Majrūr — состояние имени, которое появляется, когда слово грамматически зависит от того, что стоит перед ним.', 'Как определить: самые частые два случая — 1) перед словом стоит предлог (حرف جر), например فِي, مِنْ, لِـ; 2) слово является второй частью идафы — مُضَاف إِلَيْهِ (muḍāf ilayhi), то есть уточняет первое имя. В идафе можно мысленно спросить не «какой падеж?», а «чего / кого именно?» — но это лишь подсказка для смысла, а грамматически majrūr определяется самой конструкцией.', 'В нашей фразе خَيْرَ ٱلزَّادِ (khayra al-zādi) — идафа. خَيْرَ (khayra) — первая часть, مُضَاف (muḍāf), а ٱلزَّادِ (al-zādi) — вторая, مُضَاف إِلَيْهِ (muḍāf ilayhi). Именно положение второй части идафы делает ٱلزَّادِ majrūr. И только затем мы замечаем показатель формы: здесь -i / kasra — al-zādi.'], en: ['Majrūr is the state a noun takes when it is grammatically dependent on something before it.', 'The two most common triggers are: a preceding preposition, or being the second noun of an iḍāfa as مُضَاف إِلَيْهِ. A meaning question like “of what / whose?” can sometimes help in an iḍāfa, but the grammatical state comes from the construction itself.', 'Here خَيْرَ ٱلزَّادِ (khayra al-zādi) is an iḍāfa. خَيْرَ is the muḍāf and ٱلزَّادِ is the muḍāf ilayhi. That second position makes ٱلزَّادِ majrūr; the final -i / kasra is then the visible marker.'] },
  nominative: { ar: 'مَرْفُوع', tr: 'marfūʿ', words: [26], tone: 'c', aliases: ['marfūʿ','مَرْفُوع'], ru: ['Marfūʿ — состояние, которое часто получают слова, выполняющие основные «опорные» роли в предложении: например, действующее лицо (فاعل), مبتدأ (mubtadaʾ), خبر (khabar), а также خبر إِنَّ (khabar inna).', 'Как определить: сначала выясняем, какую работу делает слово. Если оно сообщает, кто совершает действие, с чего начинается именное высказывание или что говорится о названном предмете, оно часто будет marfūʿ. Но снова: не один вопрос определяет состояние — его определяет конкретная грамматическая роль.', 'В нашей фразе ٱلتَّقْوَىٰ (al-taqwā) — خبر إِنَّ (khabar inna). То есть после خَيْرَ ٱلزَّادِ (khayra al-zādi) — «лучший запас» — именно ٱلتَّقْوَىٰ сообщает, чем этот «лучший запас» является. Роль khabar inna требует marfūʿ. Обычно marfūʿ можно увидеть по -u / ḍamma, но تَقْوَىٰ (taqwā) заканчивается на ىٰ (alif maqṣūra), поэтому эта ḍamma остаётся скрытой.'], en: ['Marfūʿ is the state commonly used for core sentence roles such as the doer (فاعل), مبتدأ, خبر, and خبر إِنَّ.', 'To identify it, determine the word’s function first: a word naming the doer, beginning a nominal statement, or completing what is said about something is often marfūʿ. No single question defines the state; the syntactic role does.', 'Here ٱلتَّقْوَىٰ (al-taqwā) is خبر إِنَّ (khabar inna): it tells us what خَيْرَ ٱلزَّادِ (khayra al-zādi), “the best provision,” is. That role requires marfūʿ. A ḍamma would normally mark it, but the final ىٰ hides that vowel.'] },
  damma: { ar: 'ضَمَّة مُقَدَّرَة', tr: 'ḍamma muqaddara', words: [26], tone: 'c', aliases: ['дамма','ḍamma'], ru: ['Подразумеваемая ḍamma: состояние marfūʿ определяется грамматической функцией слова, но сама огласовка здесь не видна и отдельно не произносится.', 'تَقْوَىٰ (taqwā) заканчивается на ىٰ (alif maqṣūra). Поэтому состояние слова определяется по его роли خبر إِنَّ (khabar inna), а не по видимому значку ُ.'], en: ['An understood ḍamma: the case is grammatically present, but the vowel is not written or pronounced separately.', 'تَقْوَىٰ ends in ىٰ (alif maqṣūra). Its marfūʿ state is understood from its role as khabar inna.'] },
  alif: { ar: 'أَلِف مَقْصُورَة', tr: 'alif maqṣūra', words: [26], tone: 'c', aliases: ['alif maqṣūra'], ru: ['Название конечной буквы ىٰ в تَقْوَىٰ (taqwā).', 'Именно это окончание объясняет, почему при состоянии marfūʿ ожидаемая ḍamma не видна и отдельно не произносится.'], en: ['The name of the final letter ىٰ in تَقْوَىٰ.', 'In this analysis, this ending explains why the ḍamma associated with the marfūʿ state is not displayed or separately pronounced.'] },
}
export const STEP_ROLES = {
  inna: [{ word:23, term:'inna' }, { word:24, term:'ismInna' }],
  idafa: [{ word:24, term:'mudaf' }, { word:25, term:'mudafIlayhi' }],
  predicate: [{ word:24, term:'ismInna' }, { word:25, term:'mudafIlayhi' }, { word:26, term:'khabarInna' }],
}
