// Terminology explanations grounded in the existing 2:197 token-26 analysis.
// These describe the displayed construction, not new dependency annotations.
export const SYNTAX_TERMS = {
  inna: { ar: 'إِنَّ', tr: 'inna', words: [23], tone: 'a', aliases: ['إِنَّ'], ru: ['Частица, которая вводит и усиливает утверждение.', 'В этой фразе после إِنَّ (inna) идёт خَيْرَ ٱلزَّادِ (khayra al-zādi) — «лучший запас», а ٱلتَّقْوَىٰ (al-taqwā) завершает сообщение о нём.'], en: ['A particle that introduces and emphasizes a statement.', 'Here خَيْرَ ٱلزَّادِ names “the best provision,” and ٱلتَّقْوَىٰ completes the statement about it.'] },
  ismInna: { ar: 'اسْم إِنَّ', tr: 'ism inna', words: [24], tone: 'a', aliases: ['اسم إِنَّ', 'ism inna'], ru: ['Именная часть конструкции с إِنَّ (inna): то, о чём делается утверждение.', 'Здесь эту роль выполняет خَيْرَ (khayra). После إِنَّ оно находится в состоянии manṣūb и одновременно является первым словом идафы خَيْرَ ٱلزَّادِ (khayra al-zādi).'], en: ['The nominal argument of إِنَّ: what the statement is about.', 'Here this role belongs to خَيْرَ. It is accusative and also the first noun in the iḍāfa خَيْرَ ٱلزَّادِ.'] },
  mudaf: { ar: 'مُضَاف', tr: 'muḍāf', words: [24], tone: 'a', aliases: ['مُضَاف', 'مُضاف', 'muḍāf'], ru: ['Первое слово идафы; следующее существительное уточняет его.', 'Здесь это خَيْرَ (khayra) — «лучший». ٱلزَّادِ (al-zādi) уточняет его: вместе خَيْرَ ٱلزَّادِ (khayra al-zādi) означает «лучший запас». Состояние manṣūb у خَيْرَ связано с его ролью اسم إِنَّ (ism inna).'], en: ['The first noun of an iḍāfa, specified by the noun that follows.', 'Here it is خَيْرَ, “best.” ٱلزَّادِ specifies provision. The accusative of خَيْرَ comes from its role as ism inna.'] },
  mudafIlayhi: { ar: 'مُضَاف إِلَيْهِ', tr: 'muḍāf ilayhi', words: [25], tone: 'b', aliases: ['مُضَاف إِلَيْهِ', 'مُضاف إليه', 'muḍāf ilayhi'], ru: ['Второе слово идафы: оно уточняет первое и получает состояние majrūr.', 'Здесь это ٱلزَّادِ (al-zādi) — «запас». Оно соединяется с خَيْرَ (khayra) в одну конструкцию. Именно ٱلزَّادِ, а не вся фраза, выполняет роль مُضَاف إِلَيْهِ (muḍāf ilayhi).'], en: ['The second noun of an iḍāfa. It specifies the first and is in the majrūr state.', 'Here it is ٱلزَّادِ, “provision.” This word, rather than the whole phrase, is highlighted as muḍāf ilayhi.'] },
  idafa: { ar: 'إِضَافَة', tr: 'iḍāfa', words: [24,25], tone: 'a', aliases: ['идафу', 'идафы', 'идафа', 'iḍāfa'], ru: ['Соединение двух существительных: второе уточняет первое.', 'В خَيْرَ ٱلزَّادِ (khayra al-zādi) خَيْرَ (khayra) — مُضَاف (muḍāf), а ٱلزَّادِ (al-zādi) — مُضَاف إِلَيْهِ (muḍāf ilayhi). Вместе они обозначают «лучший запас».'], en: ['A construction in which the second noun specifies the first.', 'In خَيْرَ ٱلزَّادِ, the first is muḍāf and the second is muḍāf ilayhi. Together they name “the best provision.”'] },
  khabarInna: { ar: 'خَبَر إِنَّ', tr: 'khabar inna', words: [26], tone: 'c', aliases: ['خبر إِنَّ','khabar inna'], ru: ['Часть конструкции с إِنَّ (inna), которая сообщает что-либо об её именной части и завершает утверждение.', 'Здесь ٱلتَّقْوَىٰ (al-taqwā) сообщает, чем является خَيْرَ ٱلزَّادِ (khayra al-zādi) — «лучший запас». В этой роли слово находится в состоянии marfūʿ; из-за конечной ىٰ видимая ḍamma не появляется.'], en: ['The part that completes the statement about the nominal argument of إِنَّ.', 'Here ٱلتَّقْوَىٰ says what “the best provision” is. It is in the marfūʿ state, although its final ىٰ does not display a ḍamma.'] },
  accusative: { ar: 'مَنْصُوب', tr: 'manṣūb', words: [24], tone: 'a', aliases: ['manṣūb','مَنْصُوب'], ru: ['Manṣūb — грамматическое состояние изменяемого имени, которое появляется при определённых синтаксических ролях. Оно помогает увидеть, какую функцию слово выполняет внутри фразы.'], en: ['Manṣūb is a grammatical state of an inflected noun that appears in particular syntactic roles. It helps show what function the word performs in the phrase.'], cases: { ru: ['слово является прямым объектом действия — مَفْعُول بِهِ (mafʿūl bihi)', 'слово является اسم إِنَّ (ism inna) после إِنَّ (inna) и её сестёр', 'слово является خبر كَانَ (khabar kāna) после كَانَ (kāna) и её сестёр', 'слово выполняет роль حَال (ḥāl) — описывает состояние участника во время действия', 'слово выполняет роль تَمْيِيز (tamyīz) — уточняет значение перед ним', 'слово выступает обстоятельством времени или места — ظَرْف (ẓarf)'] , en: ['the word is a direct object — مَفْعُول بِهِ (mafʿūl bihi)', 'the word is اسم إِنَّ (ism inna) after إِنَّ (inna) and its sisters', 'the word is خبر كَانَ (khabar kāna) after كَانَ (kāna) and its sisters', 'the word functions as حَال (ḥāl), describing a participant’s state during an action', 'the word functions as تَمْيِيز (tamyīz), clarifying a preceding expression', 'the word functions as an adverbial of time or place — ظَرْف (ẓarf)'] } },
  genitive: { ar: 'مَجْرُور', tr: 'majrūr', words: [25], tone: 'b', aliases: ['majrūr','مَجْرُور'], ru: ['Majrūr — грамматическое состояние имени, которое появляется через зависимость от предлога или от другого имени. Оно показывает связь слова с предыдущим элементом конструкции.'], en: ['Majrūr is a grammatical state of a noun that appears through dependence on a preposition or another noun. It shows the word’s relationship to a preceding element.'], cases: { ru: ['перед словом стоит предлог — حَرْف جَرّ (ḥarf jarr), например فِي (fī), مِنْ (min), لِـ (li-)', 'слово является второй частью идафы — مُضَاف إِلَيْهِ (muḍāf ilayhi)', 'слово является прилагательным — نَعْت (naʿt), которое согласуется с существительным в состоянии majrūr', 'слово присоединено союзом — عَطْف (ʿaṭf) — к слову в состоянии majrūr', 'слово является приложением или пояснением к имени в состоянии majrūr'] , en: ['a preposition — حَرْف جَرّ (ḥarf jarr) — comes before the word, such as فِي (fī), مِنْ (min), or لِـ (li-)', 'the word is the second noun of an iḍāfa — مُضَاف إِلَيْهِ (muḍāf ilayhi)', 'the word is an adjective — نَعْت (naʿt) — agreeing with a majrūr noun', 'the word is joined by coordination — عَطْف (ʿaṭf) — to a majrūr word', 'the word is an appositional or explanatory dependent of a majrūr noun'] } },
  nominative: { ar: 'مَرْفُوع', tr: 'marfūʿ', words: [26], tone: 'c', aliases: ['marfūʿ','مَرْفُوع'], ru: ['Marfūʿ — грамматическое состояние имени, которое часто встречается у основных участников и частей сообщения. Оно помогает увидеть, какое слово является опорой действия или утверждения.'], en: ['Marfūʿ is a grammatical state of a noun commonly found in core participants and statement roles. It helps identify words that anchor an action or assertion.'], cases: { ru: ['слово является действующим лицом — فَاعِل (fāʿil)', 'слово является заместителем действующего лица в пассивной конструкции — نَائِب فَاعِل (nāʾib fāʿil)', 'слово является مبتدأ (mubtadaʾ) — начальной именной частью высказывания', 'слово является خبر (khabar) — сообщением о مبتدأ', 'слово является اسم كَانَ (ism kāna) после كَانَ (kāna) и её сестёр', 'слово является خبر إِنَّ (khabar inna) после إِنَّ (inna) и её сестёр'] , en: ['the word is the doer — فَاعِل (fāʿil)', 'the word is the passive-subject substitute — نَائِب فَاعِل (nāʾib fāʿil)', 'the word is مبتدأ (mubtadaʾ), the opening nominal element of a statement', 'the word is خبر (khabar), what is said about the mubtadaʾ', 'the word is اسم كَانَ (ism kāna) after كَانَ (kāna) and its sisters', 'the word is خبر إِنَّ (khabar inna) after إِنَّ (inna) and its sisters'] } },
  damma: { ar: 'ضَمَّة مُقَدَّرَة', tr: 'ḍamma muqaddara', words: [26], tone: 'c', aliases: ['дамма','ḍamma'], ru: ['Подразумеваемая ḍamma: состояние marfūʿ определяется грамматической функцией слова, но сама огласовка здесь не видна и отдельно не произносится.', 'تَقْوَىٰ (taqwā) заканчивается на ىٰ (alif maqṣūra). Поэтому состояние слова определяется по его роли خبر إِنَّ (khabar inna), а не по видимому значку ُ.'], en: ['An understood ḍamma: the case is grammatically present, but the vowel is not written or pronounced separately.', 'تَقْوَىٰ ends in ىٰ (alif maqṣūra). Its marfūʿ state is understood from its role as khabar inna.'] },
  alif: { ar: 'أَلِف مَقْصُورَة', tr: 'alif maqṣūra', words: [26], tone: 'c', aliases: ['alif maqṣūra'], ru: ['Название конечной буквы ىٰ в تَقْوَىٰ (taqwā).', 'Именно это окончание объясняет, почему при состоянии marfūʿ ожидаемая ḍamma не видна и отдельно не произносится.'], en: ['The name of the final letter ىٰ in تَقْوَىٰ.', 'In this analysis, this ending explains why the ḍamma associated with the marfūʿ state is not displayed or separately pronounced.'] },
}
export const STEP_ROLES = {
  inna: [{ word:23, term:'inna' }, { word:24, term:'ismInna' }],
  idafa: [{ word:24, term:'mudaf' }, { word:25, term:'mudafIlayhi' }],
  predicate: [{ word:24, term:'ismInna' }, { word:25, term:'mudafIlayhi' }, { word:26, term:'khabarInna' }],
}
